"""
    Copyright 2014 Leandro Israel Pinto
	
	This file is part of ICARU_FB.

    ICARU_FB is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ICARU_FB is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with ICARU_FB.  If not, see <http://www.gnu.org/licenses/>.
"""

import xml.etree.ElementTree as ET

import os
import sys
from flags import *



AppPath = os.path.dirname(sys.argv[0])
#AppPath = os.getcwd()

LYBRARY=[]
#LYBRARY=['SUBSCRIBE_2','PUBLISH_2','E_RESTART','START', 'E_CYCLE','E_DELAY','SUB_2','PUB_2','IO_READER','IO_READER_REAL','IO_WRITER', 'E_SPLIT','RECONFSTART']

def SetAppPath(ap):
	global AppPath
	AppPath = ap

def genFBType(root,outdir):
	stname = root.attrib['Name']+'.st'
	f = open(os.path.join(outdir,root.attrib['Name']+'.st'), 'w')
	fev = open(os.path.join(outdir,root.attrib['Name']+'.ev'), 'w')
	fvtype = open(os.path.join(outdir,root.attrib['Name']+'.vt'), 'w')
	
	
	if(root.attrib["Name"] in LYBRARY):
		print "Using from lib for '%s'." % (root.attrib["Name"])
		
		libp = os.path.join(AppPath, 'library')
		sf = open(os.path.join(libp , root.attrib["Name"]+'.st'))
		f.write(sf.read())
		se = open(os.path.join(libp , root.attrib["Name"]+'.ev'))
		fev.write(se.read())
		
		
		sf.close()
		se.close()
		f.close()
		fev.close()
		return
		
		
	f.write("(* Generated by xml2st *)\n")
	fev.write("# Generated by xml2st \n")
	f.write('FUNCTION_BLOCK %s\n' % (root.attrib["Name"]))
	
	#ev
	evIn = root.find('InterfaceList').find('EventInputs')	
	
	f.write('  EVENT_INPUT\n')
	#fev.write("Events = []\n")
	if evIn != None:
		for ev in evIn:
			f.write('    %s;\n' % (ev.get('Name')))
			#fev.write("Events.append(\""+ev.get('Name')+"\")\n")
			fev.write(" "+ev.get('Name')+" ")
	f.write('  END_EVENT\n')
	
	evIn = root.find('InterfaceList').find('EventOutputs')	
	f.write('  EVENT_OUTPUT\n')
	if evIn != None:
		for ev in evIn:
			f.write('    %s;\n' % (ev.get('Name')))
			fev.write(" "+ev.get('Name')+" ")
	f.write('  END_EVENT\n\n')
	
	#ecc
	evIn = root.find('BasicFB').find('ECC')	
	f.write('  EC_STATES\n')
	for ev in evIn.findall('ECState'):
		f.write("    %s" % (ev.get('Name')))
		actions = ev.findall('ECAction')
		second=False
		for act in actions:
			if(second):
				f.write(', ')
			else:
				f.write(': ')
			second = True
			if('Algorithm' in act.attrib
			and 'Output' in act.attrib):				
				f.write("%s -> %s" % (act.get('Algorithm'),act.get('Output')))
			elif('Algorithm' in act.attrib):
				f.write("%s ->" % (act.get('Algorithm')))
			elif('Output' in act.attrib):
				f.write("-> %s" % (act.get('Output')))
		f.write(";\n")
		"""
		#print "ACT ==>", ev
		if(act != None):
			if('Name' in ev.attrib
				and 'Algorithm' in act.attrib
				and 'Output' in act.attrib):
				f.write('    %s: %s -> %s;\n' 
					% (ev.get('Name'), act.get('Algorithm'), 
					act.get('Output')))
			else:
				if('Name' in ev.attrib
					and 'Algorithm' in act.attrib
					):
					f.write('    %s: %s;\n' 
						% (ev.get('Name'), act.get('Algorithm')
						))	
				if('Name' in ev.attrib
					and 'Output' in act.attrib
					):
					f.write('    %s: -> %s;\n' 
						% (ev.get('Name'), 
						act.get('Output')))			
						
		else:
			f.write('    %s;\n' % (ev.get('Name')))
			
		"""	
			
	f.write('  END_STATES\n\n')
	f.write('  EC_TRANSITIONS\n')
	for ev in evIn.findall('ECTransition'):
		f.write("    %s TO %s := %s;\n" % 
			(ev.attrib["Source"],ev.attrib["Destination"],ev.attrib["Condition"]))
	f.write('  END_TRANSITIONS\n\n')
	
	
	
	#vars
	evIn = root.find('InterfaceList').find('InputVars')	
	f.write('  VAR_INPUT\n')
	if evIn != None:
		for ev in evIn:
			if(ev.get('InitialValue')):
				f.write('    %s: %s:=%s;\n' % (ev.get('Name'), ev.get('Type'), ev.get('InitialValue')))
			else:
				f.write('    %s: %s;\n' % (ev.get('Name'), ev.get('Type')))
			fvtype.write('%s:%s;\n' % (ev.get('Name'), ev.get('Type')))
	f.write('  END_VAR\n\n')
	
	evIn = root.find('InterfaceList').find('OutputVars')	
	f.write('  VAR_OUTPUT\n')
	if evIn != None:
		for ev in evIn:
			if(ev.get('InitialValue')):
				f.write('    %s: %s:=%s;\n' % (ev.get('Name'), ev.get('Type'), ev.get('InitialValue')))
			else:
				f.write('    %s: %s;\n' % (ev.get('Name'), ev.get('Type')))
			fvtype.write('%s:%s;\n' % (ev.get('Name'), ev.get('Type')))
	f.write('  END_VAR\n\n')
	
	#internal vars
	evIn = root.find('BasicFB').find('InternalVars')	
	f.write('  VAR\n')
	if evIn != None:
		for ev in evIn:
			if(ev.get('InitialValue')):
				f.write('    %s: %s:=%s;\n' % (ev.get('Name'), ev.get('Type'), ev.get('InitialValue')))
			else:
				f.write('    %s: %s;\n' % (ev.get('Name'), ev.get('Type')))
			fvtype.write('%s:%s;\n' % (ev.get('Name'), ev.get('Type')))
	f.write('  END_VAR\n\n')
	
	#algorithms
	evIn = root.find('BasicFB').findall('Algorithm')	
	for alg in evIn:
		f.write('  ALGORITHM %s IN ST:\n' % (alg.attrib['Name']))
		
		
		a = alg.find('ST')
		#f.write('%s\n' % (a.attrib["Text"]))
		if a.text != None:
			f.write('%s\n' % (a.text))
		f.write('  END_ALGORITHM\n\n')
	
	f.write("END_FUNCTION_BLOCK\n")
	
	f.close()
	fev.close()
	#r = subprocess.call(["ieccomp.exe", "-o", Output, Output+"/"+root.attrib["Name"]+".st"])
	return stname
	
	
def read(filename, outdir):
	tree = ET.parse(filename)
	root = tree.getroot()
	#log.write('Processing '+filename)
	if(root.tag == 'FBType'):
		return genFBType(root, outdir)
	else:
		print 'File is not a FB.'
	return None
	#print root.tag
	
	
if __name__ == "__main__":
	odir = os.getcwd()
	if flagExist('-o'):
		odir = getPPar('-o')
	read(sys.argv[1], odir)
	